movabletype/movabletype

lib/MT/CMS/Entry.pm
lib/MT/CMS/Template.pm

1. Delete an entry by DataAPI.
1. Save a template by DataAPI.
Error does not occur and a success log is saved.
Get an error (see below) and an error log is saved.
（But delete entry or save template is success.）
```
内部コールバックでエラーが発生しました: Can't locate object method "autosave_session_obj" via package "MT::App::DataAPI" at lib/MT/CMS/Entry.pm line 2929.
```
```
内部コールバックでエラーが発生しました: Can't locate object method "autosave_session_obj" via package "MT::App::DataAPI" at lib/MT/CMS/Template.pm line 1852.
```
- MT 6.1
- DataAPI JavaScript SDK 0.1.0 (Try it with Node.js edition) 
I made this patch referring to 87eeecb2.

Fixed some DataAPI callback errors.

---

t/lib/MT/Test.pm

The line causes some tests to be interrupted (when some db is broken or so).
I guess the infinite sleep is not intended.
> http://perldoc.perl.org/functions/sleep.html
> Causes the script to sleep for (integer) EXPR seconds, or forever if no argument is given

Avoid infinit sleep on tests

---

t/09-image-gd-transparency.t
t/09-image-metadata.t
t/09-image-netpbm-transparency.t
t/62-asset-metadata.t

Following test fails not being skipped if netpbm driver is missing.
- t/09-image-netpbm-transparency.t
Following tests fail not being skipped if at least a driver is missing.
- t/09-image-metadata.t
- t/62-asset-metadata.t
This PR fixes the issues.
Let me explain the first case a little. Autoloaded MT::ConfigMgr->Setting(...) methods can only overwrite the value of Setting but create new key.
t/09-image-netpbm-transparency.t
```
my $cfg = MT::ConfigMgr->instance;
$cfg->ImageDriver('NetPBM'); # FAILS and fallbacks to ImageMagick
```
In order to set ImageDriver properly you should initialize the config beforehand. The minimal code for the purpose might be MT->config.
```
my $cfg = MT->config;
$cfg->ImageDriver('NetPBM');
```

Skip image driver dependent tests in case of lack of them

---

.travis.yml
t/cpanfile
t/lib/MT/Test/Env.pm

This PR also includes:
* a change to perlbrew perl so that we can add more perls to test (esp. when we make a release)
* a change to use Imager as an image driver, because Image::Magick is harder to install into perlbrew perl
* caching dependencies installed under local/, which makes total testing time shorter
* parallel testing using -j4 and MySQLPool plugin

Use more travis matrix

---

lib/MT.pm

- This PR fixes various path issues when MT_CONFIG is set to a different directory from MT_DIR
- POD in MT.pm clearly states that mt_dir is the efault base path under which MT's core templates are found.
- That being said, for bugward compatibility, it's better to fall back to mt_dir only when config_dir + path does not exist

Base path for TemplatePath etc should be mt_dir

---

lib/MT/ContentData.pm
lib/MT/ContentType.pm
lib/MT/Core.pm
lib/MT/Util.pm

- This makes it easier to regenerate fixture, and to test/debug json output
- but this also makes it slower to encode json (for now) because to_json doesn't reuse the encoder object (+ canonicalization itself)
- MT_SKIP_JSON_CANONICALIZATION to ignore canonicalization (though YAGNI, maybe for testing?)
- Consider to cache encoder object(s) if only a few fixed options are used

Canonicalize JSON encoding

---

lib/MT/CMS/Plugin.pm

https://movabletype.atlassian.net/browse/MTC-25022
* Fix failed test
* It's better that the result of list_plugins endpoint is uniquely determined

Sort resources of plugin. MTC-25022

---

lib/MT/ContentFieldType.pm
tmpl/cms/content_field_type_options/content_type.tmpl

https://movabletype.atlassian.net/browse/MTC-25080

Remove can_add option from content type field. MTC-25080

---

lib/MT/ContentFieldType.pm

https://github.com/movabletype/movabletype/commit/295d28b5b94adadf59efc01f4d649754d9219faa#diff-0451c02b9d39a42177d8db644fe05d80L188

Revert removed ss_validator for number field. MTC-25123

---

t/110-cms-permission-blog.t

t/110-cms-permission-blog.t without fixture fails on Shippable.

Fix failed test. MTC-25297

---

lib/MT/CMS/Blog.pm

> Use of uninitialized value $_[0] in hash element at lib/MT/App.pm line 2819.

Suppress warning after creating site 

---

lib/MT/ContentData.pm

The patch prevents the following errors.
Can't use an undefined value as an ARRAY reference at /app/movabletype/lib/MT/Revisable.pm line 125.
Can't use an undefined value as an ARRAY reference at /app/movabletype/lib/MT/Revisable/Local.pm line 119.
1. Create a content data.
2. Don't change anything and save again.

Muting errors on unchanged content data save

---

t/lib/MT/Test/Tag.pm

Sample usage:
```
for my $archive_type ( MT->publisher->archive_types ) {
MT::Test::Tag->vars->{archive_type} = $archive_type;
MT::Test::Tag->run_perl_tests($blog_id);
}
done_testing;
__DATA__
=== archives
--- template
<mt:Archives type="[% archive_type %]"><mt:ArchiveType></mt:Archives>
--- expected chomp
[% archive_type %]
```

Add MT::Test::Tag->vars

---

t/mt7/tag/archive/archive-link-index.t

@taitetsu 
#656 の修正です。
テストを見ると、下記の件は ContentType-Author-Yearly のみで、ContentType-Author-(Daily|Monthly|Weekly) では問題なさそうです。
https://movabletype.atlassian.net/browse/MTC-26127
問題なさそうでしたらマージお願いします。

Fix tests for content_type_date_based_author archives. MTC-26127

---

lib/MT/Template/Tags/ContentType.pm
php/lib/mtdb.base.php
t/mt7/tag/contents-with-fields-contenttype-category-based.t
t/mt7/tag/contents-with-fields.t

to allow a category specified in a field modifier override the category specified in the template map when both categories belong to the same category set

Fix category precedence MTC-26097 MTC-26104

---

lib/MT/Template/Tags/Entry.pm

Add test. MTC-26210

---

t/mt7/content_field.t

t/mt7/content_field.t currently passes because of a bug in Data::ObjectDriver that generates a term such as "name = NULL" (and thus MT::ContentField::_exist_same_name always returns false). Each content field created in this test should have a unique name.

Use unique content field names to test unique_id correctly

---

t/data_api/249-api-endpoint-template-v4.t

https://github.com/movabletype/movabletype/commit/58a1b372c44e075885505a16bc2a80a4fee26934
The test passes in this commit, but its fixture is old.

Fix failed test on Travis CI

---

lib/MT/Object.pm

set_values() is too late to modify datetime column value because of $dbd->need_encode

Fix empty string in datetime column earlier MTC-25999

---

lib/MT/Asset.pm
t/data_api/237-api-endpoint-asset-v3.t

cf. t/data_api/237-api-endpoint-asset-v3.t
```
prepare_cached(SELECT asset_id, asset_blog_id, asset_class, asset_created_by, asset_created_on, asset_description, asset_file_ext, asset_file_name, asset_file_path, asset_label, asset_mime_type, asset_modified_by, asset_modified_on, asset_parent, asset_url
FROM mt_asset
WHERE (asset_parent = ?)
ORDER BY asset_id ASC
) statement handle DBI::st=HASH(0xb6e2cd8) still Active at .../extlib/Data/ObjectDriver/Driver/DBI.pm line 61.
```
This warning happens because ```$a->remove``` starts another iteration.

Silence active statement warnings

---

t/lib/MT/Test/Env.pm

[MT6.5] MT::Util::is_valid_email considers ```mt@localhost``` invalid

---

t/lib/MT/Test/Env.pm

MT::Util::is_valid_email considers ```mt@localhost``` invalid

---

lib/MT.pm

Fixed perldoc bag only one line :-)
- need =back tag between =item tag and =head2 tag

Fixed perldoc bag

---

lib/MT/App/Search.pm
lib/MT/App/Search/ContentData.pm
lib/MT/CMS/Common.pm

Remove duplicated "return."
It doesn't make sense why "return" words are repeated.
If these are needed, could you tell me why?

Remove duplicated "return."

---

mt-check.cgi

HTML::Entities is now a prerequisite module for CGI but it can't be added to extlib because it uses an XS module (HTML::Parser). Fortunately mt-check.cgi only uses encode_entities so it works without HTML::Parser.

Embed a part of HTML::Entities in mt-check.cgi MTC-26980

---

t/cpanfile

cf. https://rt.cpan.org/Public/Bug/Display.html?id=130525, which breaks t/xt/dangling-symlinks.t

Mark Archive::Zip 1.66/1.67 as conflicting

---

t/mt7/tag/content-next.t
t/mt7/tag/content-previous.t

::SQL::MSSQLServer internally replaces each datetime column in a SQL statement with CONVERT(..., 20) that requires YYYY-MM-DD HH:MM:SS format
cf. https://docs.microsoft.com/ja-jp/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-2017

Use yyyy-mm-dd hh:mm:ss format

---

lib/MT/CMS/Blog.pm

I think the empty value for "commenter_id" is more appropriate for ":" than for "".

Fix a uuv warning. MTC-27233

---

lib/MT/Util.pm
t/util/html_text_transform.t

when the paragraph does not end with a block-ish tag and the next paragraph does not start with a block-ish tag

[MT7] Add two <br>s to make a blank line if necessary MTC-27190

---

mt-static/plugins/TinyMCE5/lib/js/adapter.js

cf. https://github.com/movabletype/movabletype/commit/1852ef624008a7a24558176b992ffedfc9f8b48c

[MT6] Backport adapter.js for TinyMCE5 from MT7 MTC-27489

---

t/lib/MT/Test/Env.pm

I want to run a test with mt-dev with the following command in order to test with an arbitrary database instance.
```bash
[docker-container] $ PERL_TEST_MYSQLPOOL_DSN='dbi:mysql:host=db;user=root;password=password' prove -It/lib t/*.t
```
In the normal case, I know that we can run unit tests directly using docker run with the following command.
```bash
[local] $ docker run --rm --entrypoint '' -v `pwd`:/mt -w /mt movabletype/test:perl-5.28 prove -j4 -PMySQLPool=MT::Test::Env -It/lib t/*.t
```

Make DBPassword configurable via PERL_TEST_MYSQLPOOL_DSN.

---

t/lib/MT/Test/Role/WebQuery.pm

Web::Query doesn't handle 'svg > title' properly.
```
use strict;
use warnings;
use feature qw(say);
my $str = '';
$str .= $_ while (<DATA>);
my $selector = '#test';
{
use Web::Query::LibXML;
my $b = Web::Query::LibXML->new($str);
say 'Web::Query::LibXML';
say "'". $b->find($selector)->eq(0)->html. "'";
say "'". $b->find($selector)->eq(0)->as_html. "'";
}
{
use Web::Query;
my $b = Web::Query->new($str);
say 'Web::Query';
say "'". $b->find($selector)->eq(0)->html. "'";
say "'". $b->find($selector)->eq(0)->as_html. "'";
}
__DATA__
<!DOCTYPE html>
<html lang="ja">
<body>
<a id="test"><svg role="img" class="mt-icon--inverse"><title>Open mobile global menu</title></svg></a>
</body>
</html>
```

[MT7] use Web::Query::LibXML

---

mt-static/plugins/TinyMCE/lib/js/adapter.js
mt-static/plugins/TinyMCE5/lib/js/adapter.js

https://www.tiny.cloud/docs/configure/editor-appearance/#branding

[MT7] Remove the `branding` setting and use the default value. MTC-28055

---

mt-static/plugins/TinyMCE5/lib/js/adapter.js

https://www.tiny.cloud/docs/configure/editor-appearance/#branding

[MT6]  Remove the `branding` setting and use the default value. MTC-28055

---

lib/MT.pm
lib/MT/Component.pm
lib/MT/Core.pm

Reverts movabletype/movabletype#2001

Revert "[MT6] Prevent a weird package name from being evaluated MTC-28188"

---

lib/MT/App.pm
lib/MT/Core.pm

Make sure to wait specified time if DisableMetaRefresh is true; otherwise, just wait, though the sleep may be interrupted by HUP because meta refresh does not seem to wait enough these days

[MT7] Wait after reboot MTC-28532

---

t/mt7/archive_type.t
t/template/301-archive-type-category.t

パブリッシャーのテストがCIではパスするものの、ローカルでは高頻度でフェイルするので対策しました。

make sure test file is older than 1 second on publisher test

---

mt-static/plugins/TinyMCE6/lib/js/adapter.js

The removal of "\u00a0" was added in MTC-10735, but this removal is no longer necessary now that IE is no longer supported.

Do not call `setContent` because it resets the editor's cursor state. MTC-28657

---

package-lock.json
yarn.lock

Reverts movabletype/movabletype#2485

Revert "Bump decode-uri-component from 0.2.0 to 0.2.2"

---

lib/MT/ContentData.pm

Fixed a bug that caused an error in the data identification label filter when customizing the display of the data_label on the content data list screen with a plugin.

Fixed an issue where data label filters would fail. MTC-28871

---

lib/MT/App/CMS.pm

トップレベルのメニューのsortの対策です
https://github.com/movabletype/movabletype/blob/fix/uuv_in_build_menus/lib/MT/App/CMS.pm#L3470
```
applications:
cms:
menus:
mymenu:
label: My Top Level No Order
entry:no_order:
label: No Order
```

Supress uuv more
