- extlib/IO/Socket/IP.pm
- extlib/JSON.pm
- extlib/JSON/PP.pm
- extlib/JSON/PP/Boolean.pm
- extlib/JSON/backportPP.pm
- extlib/JSON/backportPP/Boolean.pm
- IO::Socket::IP (0.24 => 0.39): silences "syswrite() on unopened filehandle" warnings
- JSON/JSON::PP (2.94 => 2.96): fix a UNIVERSAL::isa issue
> Update IO::Socket::IP and JSON

- tmpl/cms/include/primary_navigation.tmpl
https://movabletype.atlassian.net/browse/MTC-25021
> Adjust scope switch by mark-up temporarily. MTC-25021

- lib/MT.pm
- tmpl/cms/cfg_entry.tmpl
- tmpl/cms/cfg_feedback.tmpl
- tmpl/cms/cfg_system_general.tmpl
- tmpl/cms/cfg_system_users.tmpl
- tmpl/cms/cfg_web_services.tmpl
- tmpl/cms/edit_category.tmpl
- tmpl/cms/edit_entry.tmpl
- tmpl/cms/edit_role.tmpl
- tmpl/cms/edit_template.tmpl
- tmpl/cms/system_check.tmpl
- introduced "enabled_plugins" template hash variable to see which plugins are enabled
> Hide more feedback-related pieces in various templates MTC-25022

- lib/MT/Blog.pm
https://movabletype.atlassian.net/browse/MTC-25020
* Round the value that is out of range between -10 to 10.
* Empty/Invalid value is changed to 0.
> Round MT::Blog#junk_score_threshold. MTC-25020

- tmpl/cms/include/primary_navigation.tmpl
https://movabletype.atlassian.net/browse/MTC-25021
Fix bug in #75
> Fix menu icon position in site scope. MTC-25021

- mt-static/jquery/jquery.mt.js
- tmpl/cms/include/async_asset_upload.tmpl
https://movabletype.atlassian.net/browse/MTC-11678
* Delay resizing upload overlay
* Disable drop event of modal
> Fix that drop field is sometimes broken

- lib/MT/App/CMS.pm
https://movabletype.atlassian.net/browse/MTC-25027
> Fix that category_set menu is not open. MTC-25027

- mt-static/jquery/jquery.mt.js
- tmpl/cms/dialog/asset_edit.tmpl
- tmpl/cms/dialog/edit_image.tmpl
- tmpl/cms/include/async_asset_upload.tmpl
Fixed that multiple modal does not work.
https://movabletype.atlassian.net/browse/MTC-10622
> Support multiple modal. MTC-10622

- lib/MT/Website.pm
https://movabletype.atlassian.net/browse/MTC-25060
> Always show "Child Sites" after "Name" on list_site screen. MTC-25060

- tmpl/cms/content_field_type_options/number.tmpl
https://movabletype.atlassian.net/browse/MTC-25064
> Validate "number of decimal places" of number field. MTC-25064

- lib/MT/BackupRestore.pm
https://movabletype.atlassian.net/browse/MTC-11828
> Fix broken import of category and category_set. MTC-11828

- tmpl/cms/upgrade.tmpl
https://github.com/movabletype/mt7/issues/140
> Adjust button position of upgrade screen [ci skip]

- lib/MT/BackupRestore.pm
https://movabletype.atlassian.net/browse/MTC-11828?focusedCommentId=365078&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-365078
> Update category_set order after restoring. MTC-11828

- lib/MT/App/CMS.pm
https://movabletype.atlassian.net/browse/MTC-25083
> Fix that menu is not opened on edit_category screen. MTC-25083

- lib/MT/ContentFieldType/Common.pm
https://movabletype.atlassian.net/browse/MTC-25087?focusedCommentId=365200&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-365200
> Fix limit length of multi_line_text and embedded_text. MTC-25087

- lib/MT/Asset.pm
https://movabletype.atlassian.net/browse/MTC-25089
> Add ID to filter name of assets in asset field. MTC-25089

- tmpl/cms/include/anonymous_comment.tmpl
- tmpl/cms/include/comment_detail.tmpl
- tmpl/cms/include/comment_table.tmpl
- tmpl/cms/include/commenter_table.tmpl
- tmpl/cms/include/ping_table.tmpl
It turned out these templates couldn't be moved into plugins.
> Restore include templates

- lib/MT/Asset.pm
https://movabletype.atlassian.net/browse/MTC-25089
> Fix empty filter items of asset field filter. MTC-25089

- lib/MT/CMS/ContentType.pm
- lib/MT/ContentFieldType.pm
- lib/MT/ContentFieldType/Common.pm
- lib/MT/Template/ContextHandlers.pm
- lib/MT/Template/Tags/Category.pm
- mt-static/js/contenttype/tag/content-field.tag
- mt-static/js/contenttype/tag/content-fields.tag
- readme.html
- tmpl/cms/edit_content_type.tmpl
- tmpl/cms/include/main_content.tmpl
- tmpl/cms/layout/default.tmpl
This reverts commit de05b71d7e1d0bb85e4ddf6fccc293d2c73ec4d1, reversing
changes made to b535c761b0d3f59c318c90afecb8c9b5a078afa6.
@yuji 
テスト失敗してるので revert します。
> Revert "Merge branch 'redesign-edit-content-type' into develop"

- tmpl/cms/dialog/asset_edit.tmpl
- tmpl/cms/dialog/asset_options.tmpl
- tmpl/cms/edit_asset.tmpl
- tmpl/cms/edit_entry.tmpl
https://movabletype.atlassian.net/browse/MTC-11802?focusedCommentId=365248&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-365248
> Add parent div tag to .mt-suggest. MTC-11802 [ci skip]

- lib/MT/ContentData.pm
- lib/MT/Entry.pm
- tmpl/cms/include/comment_table.tmpl
- tmpl/cms/include/entry_table.tmpl
- tmpl/cms/include/ping_table.tmpl
https://movabletype.atlassian.net/browse/MTC-25104
> Use new status icons. MTC-25091

- lib/MT/Asset/Image.pm
https://movabletype.atlassian.net/browse/MTC-11725?focusedCommentId=365263&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-365263
> Fix that dimensions is not showed in asset field. MTC-11725

- lib/MT/CMS/Asset.pm
- tmpl/cms/edit_asset.tmpl
https://movabletype.atlassian.net/browse/MTC-25106?focusedCommentId=365278&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-365278
> Fix wrong icon in related_assets widget on edit_asset screen. MTC-25106

- lib/MT/Template/ContextHandlers.pm
https://movabletype.atlassian.net/browse/MTC-25109
> Adjust margin of .actions-bar. MTC-25109

- lib/MT/CMS/ContentType.pm
- lib/MT/CMS/Search.pm
- lib/MT/ContentData.pm
- lib/MT/ContentFieldType/Asset.pm
- lib/MT/ContentFieldType/Categories.pm
- lib/MT/ContentFieldType/Common.pm
- lib/MT/ContentFieldType/ContentType.pm
- lib/MT/ContentFieldType/Date.pm
- lib/MT/ContentFieldType/DateTime.pm
- lib/MT/ContentFieldType/List.pm
- lib/MT/ContentFieldType/Table.pm
- lib/MT/ContentFieldType/Tags.pm
- lib/MT/ContentFieldType/Time.pm
https://movabletype.atlassian.net/browse/MTC-25115
> Revise arguments of content_field handler. MTC-25115

- lib/MT/BackupRestore.pm
- lib/MT/BackupRestore/BackupFileHandler.pm
https://movabletype.atlassian.net/browse/MTC-11839?focusedCommentId=365398&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-365398
> Update MT::ContentType#data_label when importing site. MTC-11839

- tmpl/cms/include/primary_navigation.tmpl
https://movabletype.atlassian.net/browse/MTC-25144
> Fix typo in primary navigation. MTC-25144

- tmpl/cms/include/primary_navigation.tmpl
This reverts commit 0a6cd2acc1354afa58a9a7fd5f0912bd1570ce7b.
> Revert "Fix wrong markup. MTC-25150 [ci skip]"

- lib/MT/CMS/ContentData.pm
- lib/MT/CMS/Search.pm
- lib/MT/ContentFieldType/ContentType.pm
https://movabletype.atlassian.net/browse/MTC-25108?focusedCommentId=365384&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-365384
> Fix error when searching content_data. MTC-25108

- tmpl/cms/include/primary_navigation.tmpl
https://movabletype.atlassian.net/browse/MTC-25078
> Fix wrong width of primary navigion menu. MTC-25078 [ci skip]

- tmpl/cms/listing/log_list_header.tmpl
set max-width
https://movabletype.atlassian.net/browse/MTC-25035?focusedCommentId=365524&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-365524
> [ci skip] Set max-width to td.message on list log screen. MTC-25035

- lib/MT/Template/ContextHandlers.pm
- lib/MT/Template/Tags/ContentType.pm
https://movabletype.atlassian.net/browse/MTC-25188
> Implement static MTContentEditLink tag. MTC-25188

- tmpl/cms/field_html/field_html_categories.tmpl
- tmpl/cms/include/category_selector.tmpl
https://movabletype.atlassian.net/browse/MTC-11740?focusedCommentId=365613&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-365613
> [ci skip] Add margin to the form in categories field. MTC-11740

- lib/MT/ContentFieldType/Common.pm
https://movabletype.atlassian.net/browse/MTC-25194
> Permit all asset type in asset tag handler. MTC-25194

- lib/MT/Blog.pm
- lib/MT/CMS/Category.pm
- lib/MT/Category.pm
- t/113-cms-category.t
- MT::Blog::clone_with_children
- MT::CMS::Category::edit
- MT::Category::save
> Move more feedback stuff to plugins

- lib/MT/Template/ContextHandlers.pm
- lib/MT/Template/Tags/ContentType.pm
- t/mt7/tag/content-type-description.t
- t/mt7/tag/content-type-id.t
- t/mt7/tag/content-type-name.t
- t/mt7/tag/content-type-unique-id.t
* MTContentTypeDescription
* MTContentTypeID
* MTContentTypeName
* MTContentTypeUniqueID
https://movabletype.atlassian.net/browse/MTC-25197
> Implement content type static funcion tags. MTC-25197

- lib/MT/ContentFieldType/DateTime.pm
- lib/MT/ContentFieldType/Time.pm
https://movabletype.atlassian.net/browse/MTC-25192
> Fix format of date_and_time field and time_only field. MTC-25192

- mt-static/plugins/BlockEditor/lib/js/jquery.blockeditor.js
https://movabletype.atlassian.net/browse/MTC-25204?focusedCommentId=365736&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-365736
> [ci skip] Fix markup of adding content block in block editor. MTC-25204

- tmpl/cms/include/async_asset_upload.tmpl
https://movabletype.atlassian.net/browse/MTC-11734
> [ci skip] Adjust height of upload card. MTC-11734

- tmpl/cms/layout/common/header.tmpl
https://movabletype.atlassian.net/browse/MTC-25225
> [ci skip] Remove "overflow: visible;" from body tag. MTC-25225

- tmpl/cms/edit_content_data.tmpl
- tmpl/cms/edit_entry.tmpl
https://movabletype.atlassian.net/browse/MTC-25228
> [ci skip] Add margin to delete button on edit content screens. MTC-25228

- lib/MT/BackupRestore/BackupFileHandler.pm
- lib/MT/ContentData.pm
- lib/MT/ContentField.pm
- lib/MT/ContentType.pm
- lib/MT/ContentType/UniqueID.pm
https://movabletype.atlassian.net/browse/MTC-25251
> Improve unique_id

- lib/MT/XMLRPCServer.pm
- t/28-xmlrpc.t
https://movabletype.atlassian.net/browse/MTC-25179
> Do not load categories for category set in mt-xmlrpc.cgi. MTC-25179

- lib/MT/AtomServer.pm
- t/41-atom.t
https://movabletype.atlassian.net/browse/MTC-25252
> Do not load categories for category set in mt-atom.cgi. MTC-25252

- tmpl/cms/include/async_asset_list.tmpl
https://movabletype.atlassian.net/browse/MTC-25243?focusedCommentId=365909&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-365909
> [ci skip] Add margin to asset modal. MTC-25243

- mt-static/js/tc/tagcomplete.js
https://movabletype.atlassian.net/browse/MTC-25111
> [ci skip] Fix that tag suggest does not work on IE11. MTC-25111

- lib/MT/ContentData.pm
https://movabletype.atlassian.net/browse/MTC-25230?focusedCommentId=365914&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-365914
> Fix error of content field sort. MTC-25230

- lib/MT/App/Search/ContentData.pm
https://movabletype.atlassian.net/browse/MTC-11858?focusedCommentId=365915&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-365915
> Fix that content field filter does not work. MTC-11858

- lib/MT/ContentData.pm
https://movabletype.atlassian.net/browse/MTC-25267
> Fix wrong list_properties for content data. MTC-25267

- lib/MT/App/CMS.pm
https://movabletype.atlassian.net/browse/MTC-25258
> Add content_data_id to state_params. MTC-25258

- lib/MT/Summary/Author.pm
- t/91-tagcoverage.t
https://movabletype.atlassian.net/browse/MTC-25271
> Move code of MTAuthorCommentCount tag to plugins. MTC-25271

- mt-static/js/listing/list_store.js
- mt-static/js/listing/listing.js
- mt-static/js/listing/tag/list-top.tag
- tmpl/cms/list_common.tmpl
https://movabletype.atlassian.net/browse/MTC-25278
> Implement listReady event to list_common screen. MTC-25278

- mt-static/js/listing/listing.js
- mt-static/js/listing/tag/list-top.tag
https://movabletype.atlassian.net/browse/MTC-25289
> [ci skip] Fix broken listing screen on IE 11. MTC-25289

- tmpl/cms/dialog/adjust_sitepath.tmpl
https://movabletype.atlassian.net/browse/MTC-25172
> Remove empty modal when importing site. MTC-25172

- mt-static/js/tc/tagcomplete.js
https://movabletype.atlassian.net/browse/MTC-25112?focusedCommentId=366169&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-366169
> [ci skip] Fix tag-suggest bugs

- lib/MT/CMS/ContentType.pm
https://movabletype.atlassian.net/browse/MTC-25352
> Forbid opening list_content_data screen with invalid blog_id. MTC-25352

- lib/MT/CMS/ContentType.pm
https://movabletype.atlassian.net/browse/MTC-25353
> Forbid opening edit_content_type screen with invalid blog_id. MTC-25353

- lib/MT/App/CMS.pm
- lib/MT/CMS/CategorySet.pm
https://movabletype.atlassian.net/browse/MTC-25354
> Forbid opening edit_category_set screen with invalid blog_id. MTC-25354

- lib/MT/Entry.pm
also fix folder filter for page
https://movabletype.atlassian.net/browse/MTC-25362
> Fix category filter for entry. MTC-25362

- lib/MT/CMS/Category.pm
https://movabletype.atlassian.net/browse/MTC-25359?focusedCommentId=366454&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-366454
> Fix conflict of category basename. MTC-25359

- mt-static/mt.js
- tmpl/cms/layout/modal/footer.tmpl
https://movabletype.atlassian.net/browse/MTC-25390
> Fix bug that modal does not close. MTC-25390

- lib/MT/Util.pm
https://movabletype.atlassian.net/browse/MTC-25395
> Make timeout in FacebookCommenters plugin short. MTC-25395

- package.json
cherry-picked from support-7.0x branch
https://github.com/movabletype/movabletype/pull/338
> Fix "npm run test-riot" on Travis CI

- lib/MT/CMS/Blog.pm
https://movabletype.atlassian.net/browse/MTC-25447
>  Fix broken select_weblog modal after searching. MTC-25447

- lib/MT/CMS/Common.pm
- lib/MT/CMS/User.pm
- tmpl/cms/edit_author.tmpl
... other system administrator. MTC-25399
https://movabletype.atlassian.net/browse/MTC-25399
> Fix bug that system administrator cannot change system permissions of

- lib/MT/Upgrade/v7.pm
- t/class/upgrade-v7-migrate-blog-templatemap-archive-type.t
https://movabletype.atlassian.net/browse/MTC-25481
>  Fix templatemap upgrading error. MTC-25481

- shippable.yml
- t/110-cms-permission-comment.t
https://movabletype.atlassian.net/browse/MTC-25483
> Fix CI failure. MTC-25483

- lib/MT/FileMgr/Local.pm
- t/10-filemgr.t
https://movabletype.atlassian.net/browse/MTC-25482
> Implement MT::FileMgr::rmdir to use in Sync.pack. MTC-25482

- .travis.yml
- t/35-tags.dat
and fix failed test
https://movabletype.atlassian.net/browse/MTC-25483
> Use Docker on Travis CI. MTC-25483

- t/80-serialize-leak.t
> Fix t/80-serialize-leak.t that has looked at a different issue

- .travis.yml
https://movabletype.atlassian.net/browse/MTC-25489
> Need to install git on centos6 environment. MTC-25489

- lib/MT/App/CMS.pm
- lib/MT/ContentData.pm
- lib/MT/ContentPublisher.pm
- lib/MT/Template/Tags/Archive.pm
- lib/MT/Template/Tags/ContentType.pm
https://movabletype.atlassian.net/browse/MTC-25513
> Fix that plugin cannot add column to content data. MTC-25513

- lib/MT/App/Search/ContentData.pm
https://movabletype.atlassian.net/browse/MTC-25522
> Fix that mt-cdsearch.cgi does not search number field. MTC-25522

- lib/MT/DataAPI/Endpoint/v2/User.pm
- t/data_api/233-api-endpoint-user.t
Fix https://github.com/movabletype/movabletype/issues/368
> Set auth_type in create_user endpoint. MTC-25526

- lib/MT/ContentData.pm
https://movabletype.atlassian.net/browse/MTC-25413
> Fix mt-cdsearch.cgi for SQL Server roughly. MTC-25413

- lib/MT/ContentData.pm
https://movabletype.atlassian.net/browse/MTC-25413
I will refactor code later
> Fix mt-cdsearch.cgi for Oracle Database roughly. MTC-25413

- lib/MT/CMS/Filter.pm
- mt-static/js/listing/list_client.js
https://movabletype.atlassian.net/browse/MTC-25554
> Do not escape filter label in save_filter response. MTC-25554

- lib/MT/CMS/Filter.pm
- mt-static/js/listing/list_client.js
https://movabletype.atlassian.net/browse/MTC-25554
>  Enable to stop escaping filter label in remove_filter response. MTC-25554

- lib/MT/ContentData.pm
- lib/MT/ContentFieldType/Asset.pm
- lib/MT/ContentFieldType/Categories.pm
- lib/MT/ContentFieldType/Common.pm
- lib/MT/ContentFieldType/ContentType.pm
- lib/MT/ContentFieldType/Tags.pm
- lib/MT/ContentType.pm
https://movabletype.atlassian.net/browse/MTC-25549
> Remove empty IN operator in SQL query. MTC-25549

- lib/MT/ContentFieldType/Asset.pm
- lib/MT/ContentFieldType/Categories.pm
- lib/MT/ContentFieldType/Common.pm
- lib/MT/ContentFieldType/ContentType.pm
- lib/MT/ContentFieldType/Tags.pm
- lib/MT/Object.pm
https://movabletype.atlassian.net/browse/MTC-25549
Fix repored bugs.
> Fix errors on SQL Server or Oracle Database caused by invalid SQL. MTC-25549

- lib/MT.pm
- lib/MT/CategorySet.pm
- lib/MT/ContentType.pm
- lib/MT/Upgrade/v7.pm
- t/mt7/category_set.t
https://movabletype.atlassian.net/browse/MTC-25560
>  Fix that content_type count of category_set is always 0. MTC-25560

- lib/MT/CMS/ContentData.pm
- lib/MT/ContentFieldType.pm
- lib/MT/ContentFieldType/Common.pm
- lib/MT/ContentFieldType/ContentType.pm
https://movabletype.atlassian.net/browse/MTC-25576
> Fix preview error of content_data. MTC-25576

- lib/MT/BackupRestore.pm
https://movabletype.atlassian.net/browse/MTC-25584
> Fix that content_type_id of imported template is not updated. MTC-25584

- lib/MT/CMS/Blog.pm
an error occurs on SQL Server/Oracle Database
https://movabletype.atlassian.net/browse/MTC-25565
> Do not set class to terms of content_data. MTC-25565

- extlib/Clone/PP.pm
- lib/MT/CMS/Template.pm
- lib/MT/Theme/TemplateSet.pm
- t/class/70-theme-templatized.t
- labels may have been codified
> Use Clone::PP::clone instead of Storable::dclone MTC-25495

- lib/MT/ContentFieldType/ContentType.pm
to fix remove list_content_data screen
> Remove removed data in content_type field. MTC-25824

- php/lib/mtdb.base.php
- t/mt7/tag/contents.t
PR to https://github.com/movabletype/movabletype/pull/460
> Fix dynamic fetch_contents not to join the same table twice MTC-25829

- lib/MT/ContentData.pm
old content_type had been retrieved while importing site
> Clear MT::ContentData#content_type cache before saving. MTC-25826

- lib/MT/ContentData.pm
to suppress warnings in test
https://github.com/movabletype/movabletype/pull/469 is not good
> Do not call clear_cache against new content_data

- tmpl/cms/dialog/asset_modal.tmpl
- tmpl/cms/include/async_asset_list.tmpl
- tmpl/cms/include/async_asset_upload.tmpl
- tmpl/cms/include/insert_options_image.tmpl
> Adjust mobile upload_asset modal. MTC-25859

- t/app/144-app-wizard.t
Fix failed test of #572 and #573
> Fix failed test. MTC-25928

- Makefile
> [ci skip] Fix error on mt-sqlsrv2016 when executing "make me"

- lib/MT/ContentData.pm
- t/mt7/content_data.t
> #611 and fixed test. MTC-26019

- t/mt7/tag/archive/archive-title.t
Remove MTArchiveList tags and fix tests and results.
> Fix archive-title.t. MTC-26048

- t/lib/MT/Test/ArchiveType.pm
> Fix to use entry's author in author based archive

- t/mt7/tag/archive/archive-count.t
these will be fixed again after merging #646
> Fix failed tests in archive-count.t

- t/lib/MT/Test/Tag.pm
- t/mt7/tag/archive/archive-type-label.t
- t/mt7/tag/archive/archives.t
- t/mt7/tag/content-field.t
- t/mt7/tag/contents.t
and
* Change argument of MT::Test::Tag->run_perl_tests/run_php_tests
* Fix test name prefix
> Implement various expected sections like MT::Test::ArchiveType to MT::Test::Tag

- t/mt7/tag/archive/archive-link-index.t
@taitetsu #656 の修正です。良さそうでしたらマージしてしまってください。
> Fix wrong FIXMEs

- t/mt7/tag/archive/archive-link-archive.t
@taitetsu #656 の修正です。良さそうでしたらマージしてしまってください。
> Add entry_category stash and fix tests

- t/mt7/tag/archive/file-template.t
> Fix that file-template.t fails

- t/mt7/tag/archive/entries-archive.t
to https://github.com/movabletype/movabletype/pull/729
> Add test. MTC-26210

- lib/MT/ArchiveType/ContentTypeAuthor.pm
- php/lib/archive_lib.php
- php/lib/block.mtcontents.php
- t/mt7/tag/archive/archive-list-index.t
in static MTArchiveLis (type=ContentType-Author) and MTContents
> Fix content_type filter bug. MTC-26279

- t/mt7/content_publisher/rebuild_content_data/build_archives_archive_types.t
- t/mt7/content_publisher/rebuild_file_static.t
- t/mt7/delete_files_at_rebuild/category.t
https://app.wercker.com/miniuchi/movabletype-addons/runs
Fix some failing tests of movabletype-addons on Wercker.
> Fix failed tests on Wercker

- lib/MT/Template/Tags/ContentType.pm
- php/lib/class.mt_templatemap.php
- php/lib/mtdb.base.php
- t/mt7/archive_type.t
- t/mt7/tag/archive/archive-list-index.t
- t/mt7/tag/archive/contents-archive.t
- t/mt7/tag/contents-with-fields.t
merge after merging #761 and changing base branch to develop.
> Sort MTContents by mapping's datetime field. MTC-26228

- t/class/10-filemgr.t
> Skip tests for symlink on Win32

- t/cpanfile
- t/lib/MT/Test.pm
> Update __test_follow_redirects in MT::Test::_run_app

- lib/MT/CMS/Dashboard.pm
- lib/MT/version.pm
- t/00-compile.t
- t/class/version.t
- tmpl/cms/widget/updates.tmpl
* broken version check
* use release version if exists
> Fix update widget on dashboard. MTC-26339

- tmpl/cms/dialog/select_users.tmpl
Conflicts:
tmpl/cms/dialog/select_users.tmpl
> [MT7] Selection of a mail address for account locking was fixed. MTC-10075

- lib/MT/App.pm
- t/app/143-app.t
> [MT7] Fix $app->do_reboot not to run twice. MTC-26382

- lib/MT/App.pm
- t/143-app.t
> [MT6] Fix $app->do_reboot not to run twice. MTC-26382

- .travis.yml
> [Rokocha] Run tests without fixtures by Travis CI cron job

- lib/MT/DataAPI/Endpoint/Common.pm
and also calling handler_to_coderef once converted a handler to coderef
> Avoid calling ->registry('application', 'data_api') MTC-12955

- lib/MT/App/DataAPI.pm
- lib/MT/DataAPI/Callback/TemplateMap.pm
- lib/MT/DataAPI/Endpoint/v4/TemplateMap.pm
- t/00-compile.t
- t/data_api/270-api-endpoint-templatemap.t
cf. fix/data-api-templatemap-for-content-type-archives branch
> Add v4 TemplateMap endpoint to fix an is_preferred issue MTC-26188

- lib/MT/DataAPI/Endpoint/v4/ContentField.pm
there is no "field_label" in code
> s/field_label/type_label/. MTC-26255

- lib/MT/CMS/Template.pm
- tmpl/cms/dialog/header.tmpl
- tmpl/cms/include/header.tmpl
- tmpl/cms/include/header_popup.tmpl
- tmpl/include/chromeless_header.tmpl
> Escape screen_id for edit template screen. MTC-26486

- tmpl/cms/dialog/select_users.tmpl
> [MT6] Fix returnMemberSelection to support panels both with and without selectionList MTC-26572

- tmpl/cms/dialog/select_users.tmpl
> [MT7] Fix returnMemberSelection to support panels both with and without selectionList MTC-26572

- t/lib/MT/Test/Fixture.pm
- also store content field unique_ids in content->fields to suppress a warning
> Add prepare_template to MT::Test::Fixture

- t/lib/MT/Test/Env.pm
> Ignore DEFAULT NULL added by MariaDB 10.2.1 and later MTC-26602

- lib/MT/Template/Tags/Asset.pm
cf https://github.com/movabletype/movabletype/commit/0b6afd9a035936daa3e4e4e1d285a5fa16ed06c3#diff-747ea8a9c9685d116ce6ec0096d56811
> Check values before numerical comparison MTC-25055

- tmpl/cms/field_html/field_html_categories.tmpl
…pped short was corrected. MTC-27037
> The problem that a category name on ContentData editing screen is wrapped short was corrected. MTC-27037

- lib/MT/CMS/Entry.pm
- t/cms/cms-publish-entries.t
> entry_modified_on was updated when entry was updated in entry list screen. MTC-24805

- lib/MT/App/DataAPI.pm
- lib/MT/DataAPI/Endpoint/v2/Page.pm
- lib/MT/DataAPI/Endpoint/v3/Page.pm
- t/00-compile.t
- t/230-api-endpoint-entry-v3.t
- t/273-api-endpoint-page-v3.t
- t/lib/MT/Test/DataAPI.pm
> Add v3/create_page and v3/update_page DataAPI entrypoints MTC-10067

- build/Build.pm
> Use the registered make

- lib/MT/ObjectDriver/Driver/DBD/mysql.pm
Although it looks like an ad hoc patch, I believe it can solve the problem without affecting others.
> Use utf8mb4 if character_set_database is utf8mb4. MTC-10962

- lib/MT/WeblogPublisher.pm
> [MT6.5] Log while removing files MTC-27063

- mt-static/js/editor/editor_manager.js
This reverts commit 2f75292d05c5fe3c652d6c6d7035950e72cf5820.
> [MT7] Revert "fix add image button. MTC-25184" MTC-26287

- tmpl/cms/list_category.tmpl
MTC-27339 also modified at the same time.
> 【MT7】サブカテゴリの追加時にキーボードの Enter キーを押すとダッシュボードに戻ってしまう MTC-27255

- tmpl/cms/list_category.tmpl
MTC-27339 also modified at the same time.
> 【MT6】サブカテゴリの追加時にキーボードの Enter キーを押すとダッシュボードに戻ってしまう MTC-27255 

- lib/MT.pm
- mt-check.cgi
- php/mt.php
> Bump version. MTC-27472

- .travis.yml
- lib/MT/Util/Log.pm
- lib/MT/Util/Log/Log4perl.pm
- lib/MT/Util/Log/Minimal.pm
- t/cpanfile
- t/util/72-mt-util-log-config-log4perl.t
- t/util/72-mt-util-log.t
> [MT7] Various logger issues MTC-27748 MTC-27746

- lib/MT.pm
- mt-check.cgi
- php/mt.php
* 7.6.0 -> 7.6.1
* r.4706 -> r.4707
> Bump version. MTC-27768

- lib/MT.pm
- mt-check.cgi
- php/mt.php
> Bump version. MTC-27798

- package-lock.json
- yarn.lock
Reverts movabletype/movabletype#1682
> Revert "Bump lodash from 4.17.20 to 4.17.21"

- t/lib/MT/Test/App.pm
https://app.travis-ci.com/github/movabletype/movabletype/jobs/530116193
> fix cgi test by let Test::App pass $ENV{HTTP_*} to CGI server as header

- lib/MT/Category.pm
- t/mt7/content_data/category_count.t
> [MT7] category count for content type MTC-28337

- package-lock.json
- yarn.lock
> [MT7] Update yarn.lock

- lib/MT.pm
- mt-check.cgi
- php/mt.php
- r.5201 -> r.5202
- 7.9.3 -> 7.9.4
> Bump version. MTC-28460

- lib/MT/ObjectDriver/Driver/Cache/RAM.pm
Reverts movabletype/movabletype#2272
> Revert "[MT7] Use MT::Request as RAM cache MTC-27223"

- lib/MT/DataAPI/Resource/v2/Asset.pm
- lib/MT/Object.pm
This reverts commit 021df16f5e793484257efe64b98ffb6c41515466.
> Revert "avoid meta load on clone MTC-28068 (#2356)"

- t/selenium/cfg_prefs.t
This reverts commit 5f435a08176ce96a19ee142b2b4f267b385741f1.
> [MT7] Revert "Try wait_until_ready"

- lib/MT.pm
- mt-check.cgi
- php/mt.php
* 7.9.6 -> 7.9.7
* r.5401 -> r.5402
> Bump version. MTC-28666

- lib/MT.pm
- mt-check.cgi
- php/mt.php
* 7.9.7 -> 7.9.8
* r.5402 -> r.5403
> Bump version. MTC-28692

- tmpl/cms/dialog/header.tmpl
- tmpl/cms/dialog/move_blogs.tmpl
- tmpl/cms/dialog/select_users.tmpl
- tmpl/cms/include/header.tmpl
- tmpl/cms/include/libjs.tmpl
- tmpl/cms/list_category.tmpl
- tmpl/cms/preview_content_data_strip.tmpl
- tmpl/cms/preview_strip.tmpl
- tmpl/cms/preview_template_strip.tmpl
- tmpl/cms/upgrade_runner.tmpl
- tmpl/data_api/login.tmpl
s/name-"use_jquery_json"/name="use_jquery_json"/g
> Fix name use jquery json attribute. MTC-28706

- lib/MT/App.pm
Reverts movabletype/movabletype#2522
> Revert "[MT7] Look at SERVER_NAME first MTC-28734"

- extlib/Data/ObjectDriver.pm
- extlib/Data/ObjectDriver/Driver/DBI.pm
Reverts movabletype/movabletype#2549
> [MT7] Revert "[MT7] Update Data::ObjectDriver to 0.22 MTC-28766"

- plugins/GoogleAnalyticsV4/lib/GoogleAnalyticsV4/OAuth2.pm
> Parameter modified because refresh_token could not be obtained in some cases. MTC-28815

- lib/MT/CMS/Entry.pm
Reverts movabletype/movabletype#2580
> [MT7] Revert "[MT7] Fixed basename displayed in "Edit Entry" and "Edit Page" to match actual basename output MTC-28799"

- lib/MT.pm
- mt-check.cgi
- php/mt.php
> Bump version. MTC-28994

- mt-static/plugins/TinyMCE6/lib/js/adapter.js
Reverts movabletype/movabletype#2810
> Revert "[MT7] Use tinymce-5 skin MTC-29207" MTC-29258

- lib/MT.pm
- mt-check.cgi
- php/mt.php
> Bump version. MTC-29298

- lib/MT.pm
- mt-check.cgi
- php/mt.php
> Bump version. MTC-29436

- lib/MT.pm
- mt-check.cgi
- php/mt.php
> Bump version. MTC-29576

- lib/MT/CMS/User.pm
- t/cms/cms-role.t
- tmpl/admin2023/cms/edit_role.tmpl
- tmpl/cms/edit_role.tmpl
This reverts commit a11aadce2af581cf316c3e59aeb4dbe34d5b3678, reversing changes made to e37bbc61fc1a996219326d6b3599ba43c7287d7a.
> Revert "Merge pull request #3086 from movabletype/fix/MTC-29606"

- lib/MT/CMS/User.pm
- t/cms/cms-role.t
- tmpl/admin2023/cms/edit_role.tmpl
- tmpl/cms/edit_role.tmpl
Reverts movabletype/movabletype#3086
> Revert "Speed up edit_role.tmpl screen. MTC-29606"

- lib/MT/CMS/Entry.pm
- lib/MT/CMS/User.pm
This reverts commit c66bf36d7b99548f9f4986cafa9076dfb3006d30.
> [MT7] Revert "Return early if type and mode are not expected" MTC-29834

- lib/MT/CMS/Entry.pm
- lib/MT/CMS/User.pm
This reverts commit 7486b483019326cdd168a91dbe9b1772908cdfb0.
> [MT80] Revert "Return early if type and mode are not expected" MTC-29834

- lib/MT/CMS/Entry.pm
- lib/MT/CMS/User.pm
This reverts commit cc9a4750c4ebf45988dc1588e63353a24221942b.
> [MT8] Revert "Return early if type and mode are not expected" MTC-29834

- .github/workflows/movabletype.yml
Reverts movabletype/movabletype#3339
> Revert "[MT8] Skip selenium for now"

- lib/MT/L10N/ja.pm
- tmpl/admin2023/cms/include/footer.tmpl
- tmpl/admin2023/cms/include/old_footer.tmpl
- tmpl/cms/include/footer.tmpl
- tmpl/cms/include/old_footer.tmpl
Reverts movabletype/movabletype#3358
> Revert "[MT80] Remove obsolute links and rename Japanese feedback translation MTC-29882"

- lib/MT.pm
- mt-check.cgi
- php/mt.php
> [8.4.1] Bump version 8.4.1 MTC-29985

- lib/MT.pm
- mt-check.cgi
- php/mt.php
- 7.906.0 → 7.906.1
- r.5505 → r.5506
> [7.906.1] Bump version 7.906.1 MTC-29985

- lib/MT/CMS/Website.pm
- t/cms/website-list.t
> fix filtered_list for website MTC-30245

- lib/MT.pm
- mt-check.cgi
- php/mt.php
- 7.906.2 -> 7.906.3
- r.5507 -> r.5508
> [7.906.3] Bump version MTC-30307
